server {
    listen 8443 ssl;
    server_name nvd.nist.gov;

    ssl_certificate     /etc/nginx/certs/nvd/public-key.pem;
    ssl_certificate_key /etc/nginx/certs/nvd/private-key.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html/nvd;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }
}