name: Build and Deploy NVD Data Image

on:
  push:
    branches:
      - master
  schedule:
    # Déclenchement toutes les 6 heures (à la minute 17 : 00:17, 06:17, 12:17, 18:17 UTC)
    - cron: '17 */6 * * *'
  # Permet le lancement manuel depuis l'onglet Actions de GitHub
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Génération du tag Horodaté (Date + Heure)
        id: timestamp
        # Crée une variable de sortie au format AAAAMMJJ-HHMM (ex: 20260922-1430)
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Configuration Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nvd-data-mirror:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nvd-data-mirror:${{ steps.timestamp.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nvd-data-mirror:${{ github.sha }}